set sql_mode ='';

create table if not exists raw_data 
(
 `city`                       varchar(250)
,`source`                     varchar(250)
,`datatype`                   varchar(250)
,`receiveTime`                varchar(250)
,`PLAN_ID`                    varchar(250)
,`crawlAt`                    varchar(250)
,`housingDataType`            varchar(250)
,`keyRoute`                   varchar(250)
,`oppositeId`                 varchar(250)
,`oppositeurl`                varchar(250)
,`中介人`                     varchar(250)
,`中介人链接`                 varchar(250)
,`中介机构`                   varchar(250)
,`中介门店`                   varchar(250)
,`主体朝向`                   varchar(250)
,`二手房套数`                 varchar(250)
,`供暖方式`                   varchar(250)
,`前缀`                       varchar(250)
,`单价`                       varchar(250)
,`城市`                       varchar(250)
,`容积率`                     varchar(250)
,`小区名称`                   varchar(250)
,`小区链接`                   varchar(250)
,`建成年代`                   varchar(250)
,`建筑面积`                   varchar(250)
,`开发商`                     varchar(250)
,`总价`                       varchar(250)
,`总户数`                     varchar(250)
,`户型`                       varchar(250)
,`房源标签`                   varchar(250)
,`房源标题`                   varchar(250)
,`房源编号`                   varchar(250)
,`抓取时间`                   varchar(250)
,`月供`                       varchar(250)
,`来源`                       varchar(250)
,`楼层`                       varchar(250)
,`源描述`                     varchar(250)
,`源链接`                     varchar(250)
,`片区名称`                   varchar(250)
,`物业公司`                   varchar(250)
,`物业管理费`                 varchar(250)
,`物业类型`                   varchar(250)
,`看房时间`                   varchar(250)
,`租房套数`                   varchar(250)
,`类型`                       varchar(250)
,`纬度`                       varchar(250)
,`经度`                       varchar(250)
,`经纪人id`                   varchar(250)
,`绿化率`                     varchar(250)
,`联系电话`                   varchar(250)
,`行政区名称`                 varchar(250)
,`首付`                       varchar(250)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;